### ISSUE TITLE
[Bug] Failed to parse 0x7e (DEPOSIT) as tx type

### ISSUE THREAD

**Issue by kien-rise** [alloy-rs/op-alloy#18]
### Component

consensus, eips, genesis

### What version of Alloy are you on?

0.1.2

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
Error: DeserError { err: Error("unknown variant `0x7e`, expected one of `0x0`, `0x1`, `0x2`, `0x3`, `0x7E`",
```

The error above is encountered when I parse a deposit receipt:

<details>
<summary>Example</summary>

```yaml
# POST https://mainnet.optimism.io
{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionReceipt",
    "params":[
        "0xb7c74afdeb7c89fb9de2c312f49b38cb7a850ba36e064734c5223a477e83fdc9"
    ],
    "id":1
}
----
{
    "jsonrpc": "2.0",
    "result": {
        "blockHash": "0x9e6a0fb7e22159d943d760608cc36a0fb596d1ab3c997146f5b7c55c8c718c67",
        "blockNumber": "0x6cfef89",
        "contractAddress": null,
        "cumulativeGasUsed": "0xfa0d",
        "depositNonce": "0x8a2d11",
        "effectiveGasPrice": "0x0",
        "from": "0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001",
        "gasUsed": "0xfa0d",
        "logs": [],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "status": "0x1",
        "to": "0x4200000000000000000000000000000000000015",
        "transactionHash": "0xb7c74afdeb7c89fb9de2c312f49b38cb7a850ba36e064734c5223a477e83fdc9",
        "transactionIndex": "0x0",
        "type": "0x7e"
    },
    "id": 1720597577
}
```

</details>

### Suggested solution

```diff
# crates/consensus/src/receipt/envelope.rs
-    #[cfg_attr(feature = "serde", serde(rename = "0x7E", alias = "0x7E"))]
+    #[cfg_attr(feature = "serde", serde(rename = "0x7E", alias = "0x7e"))]

# crates/consensus/src/receipt/receipts.rs
     /// Deposit nonce for Optimism deposit transactions
-    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
+    #[cfg_attr(
+        feature = "serde",
+        serde(
+            default,
+            skip_serializing_if = "Option::is_none",
+            with = "alloy_serde::quantity::opt"
+        )
+    )]
    pub deposit_nonce: Option<u64>,
     /// Deposit receipt version for Optimism deposit transactions
-    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
+    #[cfg_attr(
+        feature = "serde",
+        serde(
+            default,
+            skip_serializing_if = "Option::is_none",
+            with = "alloy_serde::quantity::opt"
+        )
+    )]
    pub deposit_receipt_version: Option<u64>,
```
