### ISSUE TITLE
[Bug] op-alloy-network not compatible with latest alloy-provider 0.11.0

### ISSUE THREAD

**Issue by cakevm** [alloy-rs/op-alloy#423]
### Component

network

### What version of op-alloy are you on?

0.10.2

### Operating System

macOS (Apple Silicon)

### Describe the bug

It seems that op-alloy-network is not compatible with the latest alloy-provider 0.11.0. Initializing the provider results in the following compiling error:

```
error[E0599]: the method `on_http` exists for struct `ProviderBuilder<Identity, JoinFill<Identity, JoinFill<..., ...>>, ...>`, but its trait bounds were not satisfied
  --> src/main.rs:9:65
   |
9  |     let provider = ProviderBuilder::new().network::<Optimism>().on_http(rpc_url);
   |                                                                 ^^^^^^^ method cannot be called due to unsatisfied trait bounds
   |
  ::: /Users/cakevm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-provider-0.11.0/src/fillers/join_fill.rs:17:1
   |
17 | pub struct JoinFill<L, R> {
   | ------------------------- doesn't satisfy `_: TxFiller<Optimism>`
   |
  ::: /Users/cakevm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/op-alloy-rpc-types-0.10.2/src/transaction/request.rs:27:1
   |
27 | pub struct OpTransactionRequest(TransactionRequest);
   | ------------------------------- doesn't satisfy `_: TransactionBuilder4844`
   |
   = note: the full type name has been written to '/Users/cakevm/Documents/projects/rust/playground/target/debug/deps/op_alloy_example-097a72871e6a8402.long-type-1369153401551726238.txt'
   = note: consider using `--verbose` to print the full type name to the console
   = note: the following trait bounds were not satisfied:
           `op_alloy_rpc_types::transaction::request::OpTransactionRequest: TransactionBuilder4844`
           which is required by `JoinFill<GasFiller, JoinFill<BlobGasFiller, JoinFill<NonceFiller, ChainIdFiller>>>: TxFiller<Optimism>`
```

Example code:

```rust
use alloy_provider::{Provider, ProviderBuilder};
use alloy_rpc_types::BlockId;
use op_alloy_network::primitives::BlockTransactionsKind;
use op_alloy_network::Optimism;

#[tokio::main]
async fn main() -> eyre::Result<()> {
    let rpc_url = "https://base.merkle.io".parse()?;
    let provider = ProviderBuilder::new().network::<Optimism>().on_http(rpc_url);

    let block = provider.get_block(BlockId::latest(), BlockTransactionsKind::Full).await?;
    println!("Block: {:?}", block);

    Ok(())
}

```

```toml
[package]
name = "op-alloy-example"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }

# working
#alloy-provider = "0.9.2"
#alloy-rpc-types = "0.9.2"
#op-alloy-network = "0.9.2"

# not working with the latest versions <-- Thats what this issue is about
alloy-provider = "0.11.0"
alloy-rpc-types = "0.11.0"
op-alloy-network = "0.10.2"
```

Find a full example here: [op-alloy-example](https://github.com/cakevm/op-alloy-example/blob/main/Cargo.toml)
